import settings;
pdfviewer="zathura";
htmlviewer="google-chrome";
outformat="svg";
display="display";
animate="animate";
gs="gs";

import graph;
import geometry;
import math;
usepackage("physics");
usepackage("amsmath");
usepackage("amssymb");
usepackage("physics");
usepackage("amsmath");
usepackage("amssymb");
usepackage("dsfont");
texpreamble("\input{AutoColors.sty.tmp}");
texpreamble("\renewcommand{\r}{\color{Autosecondary}}");
texpreamble("\renewcommand{\b}{\color{Autoprimary}}");
label("${\b \ket{\psi}} \to {\r K_i} {\b \ket{\psi}} \text{ avec probabilité } p_i = {\b \bra{\psi}} {\r K_i^\dagger} {\r K_i} {\b \ket{\psi}}$", (0,0), fontsize(18pt));
// shipout(bbox(2mm, background, Fill));